# DATA RETRIEVE

In [23]:
import pandas as pd
from pathlib import Path
from datetime import date
import sys
from pathlib import Path

sys.path.append(str(Path("..").resolve()))

from download import download_csv

pd.set_option('display.max_colwidth', None)

csv_path = download_csv()


# Useleful data
data_to_colllect = ["id", "cp", "adresse", "ville", "gazole_maj", "gazole_prix", "sp95_maj", "sp95_prix", "e85_maj", "e85_prix", "gplc_maj", "gplc_prix", "e10_maj", "e10_prix", "sp98_maj", "sp98_prix", "geom"]

df = pd.read_csv(csv_path, sep=";", usecols=data_to_colllect)
df.shape
df.info()

cat_col = [col for col in df.columns if df[col].dtype == "str"]
num_col = [col for col in df.columns if df[col].dtype != "str"]
print(" Categorical colums ", cat_col)
print("Numerical colums", num_col)

<class 'pandas.DataFrame'>
RangeIndex: 9803 entries, 0 to 9802
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           9803 non-null   int64
 1   cp           9803 non-null   int64
 2   adresse      9803 non-null   str
 3   ville        9798 non-null   str
 4   geom         9803 non-null   str
 5   gazole_maj   8983 non-null   str
 6   gazole_prix  8983 non-null   float64
 7   sp95_maj     2770 non-null   str
 8   sp95_prix    2770 non-null   float64
 9   e85_maj      3783 non-null   str
 10  e85_prix     3783 non-null   float64
 11  gplc_maj     1492 non-null   str
 12  gplc_prix    1492 non-null   float64
 13  e10_maj      7028 non-null   str
 14  e10_prix     7028 non-null   float64
 15  sp98_maj     7058 non-null   str
 16  sp98_prix    7058 non-null   float64
dtypes: float64(6), int64(2), str(9)
memory usage: 1.3 MB
 Categorical colums  ['adresse', 'ville', 'geom', 'gazole_maj', 'sp95_maj', 'e85_maj', 'gplc_maj', 'e10_maj', 'sp98_maj']
Numerical colums ['id', 'cp', 'gazole_prix', 'sp95_prix', 'e85_prix', 'gplc_prix', 'e10_prix', 'sp98_prix']

In [17]:
# DATA SANITIZE

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 9805 entries, 0 to 9804
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           9805 non-null   int64
 1   cp           9805 non-null   int64
 2   adresse      9805 non-null   str
 3   ville        9800 non-null   str
 4   geom         9805 non-null   str
 5   gazole_maj   8917 non-null   str
 6   gazole_prix  8917 non-null   float64
 7   sp95_maj     2763 non-null   str
 8   sp95_prix    2763 non-null   float64
 9   e85_maj      3790 non-null   str
 10  e85_prix     3790 non-null   float64
 11  gplc_maj     1493 non-null   str
 12  gplc_prix    1493 non-null   float64
 13  e10_maj      7003 non-null   str
 14  e10_prix     7003 non-null   float64
 15  sp98_maj     7073 non-null   str
 16  sp98_prix    7073 non-null   float64
dtypes: float64(6), int64(2), str(9)
memory usage: 1.3 MB

,id,cp,adresse,ville,geom,gazole_maj,gazole_prix,sp95_maj,sp95_prix,e85_maj,e85_prix,gplc_maj,gplc_prix,e10_maj,e10_prix,sp98_maj,sp98_prix
0,89100001,89100,84 ROUTE DE MAILLOT,Sens,"48.183, 3.309",2026-09-28T11:45:27+00:00,2.429,NaN,NaN,2026-08-25T10:02:31+00:00,0.859,NaN,NaN,2026-09-28T11:45:27+00:00,2.209,2026-09-28T11:42:00+00:00,2.289
1,40500002,40500,Route de Mont de Marsan,Saint-Sever,"43.773, -0.567",2026-09-23T12:12:41+00:00,2.399,NaN,NaN,NaN,NaN,2026-09-02T16:40:47+00:00,1.171,2026-09-23T12:12:41+00:00,2.199,2026-09-23T12:12:41+00:00,2.350
2,80570001,80570,Rue Joliot Curie,Dargnies,"50.04475, 1.52562",2026-09-18T06:30:48+00:00,2.419,2026-09-25T06:48:02+00:00,2.249,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-25T06:48:02+00:00,2.309
3,58240003,58240,ROUTE NATIONALE 7 - LES BOULAISES,Chantenay-Saint-Imbert,"46.7535171497, 3.1406912128899998",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,38230003,38230,Rue des Ardennes,Tignieu-Jameyzieu,"45.745, 5.183",2026-09-29T01:18:00+00:00,2.365,2026-09-29T01:18:00+00:00,2.203,2026-09-29T01:18:00+00:00,0.851,2026-09-29T01:18:00+00:00,0.998,2026-09-29T01:18:00+00:00,2.162,2026-09-29T01:18:00+00:00,2.232

In [ ]:
df.describe()

,cp,gazole_prix,sp95_prix,e85_prix,gplc_prix,e10_prix,sp98_prix
count,9805.000000,8917.000000,2763.000000,3790.000000,1493.000000,7003.000000,7073.000000
mean,48884.083733,2.395345,2.227919,0.898908,1.052701,2.174282,2.276443
std,26394.916963,0.091015,0.094050,0.074417,0.090741,0.101366,0.126518
min,1000.000000,2.090000,1.549000,0.794000,0.825000,1.259000,1.339000
25%,27310.000000,2.359000,2.207000,0.859000,0.999000,2.149000,2.255000
50%,49250.000000,2.399000,2.239000,0.869000,1.040000,2.182000,2.289000
75%,71370.000000,2.448000,2.279000,0.900000,1.097000,2.219000,2.334000
max,95870.000000,2.900000,2.740000,2.249000,2.310000,2.669000,2.880000

np.int64(0)